name: Create Dragonspeak Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

#    - name: Generate unique string
#      id: unique_string
#      run: echo "::set-output name=unique_string::$(date +%Y%m%d%H%M%S)"
#######
    - name: Create release branch
      run: |
        git checkout -b release/${{ github.run_id }}
        git push origin release/${{ github.run_id }}
      continue-on-error: true

    - name: Archive code
      run: |
        # Create a ZIP archive of the main branch contents
        zip -r Dragonspeak-${{ github.run_id }}.zip .

        # Verify that the ZIP archive was created
        if [ -f Dragonspeak-${{ github.run_id }}.zip ]; then
          echo "ZIP archive created successfully."
        else
          echo "Failed to create ZIP archive."
          exit 1
        fi
      working-directory: ${{ github.workspace }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Dragonspeak-${{ github.run_id }}.zip
        path: Dragonspeak-${{ github.run_id }}.zip

    - name: Create Git tag
      run: |
        git tag v${{ github.run_id }}
        git push origin v${{ github.run_id }}

    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: Dragonspeak-${{ github.run_id }}.zip
        tag_name: v${{ github.run_id }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      ########
#    - name: Create temporary directory
#      id: create_temp_dir
#      run: mkdir -p Dragonspeak-${{ steps.unique_string.outputs.unique_string }}
#
#    - name: Copy code to temporary directory
#      run: |
#        find . -maxdepth 1 -type f -exec cp {} Dragonspeak-${{ steps.unique_string.outputs.unique_string }} \;
#      working-directory: ${{ github.workspace }}

#    - name: Archive code
#      run: |
#        cd Dragonspeak-${{ steps.unique_string.outputs.unique_string }}
#        zip -r ../Dragonspeak-${{ steps.unique_string.outputs.unique_string }}.zip .
#      working-directory: ${{ github.workspace }}
#
#    - name: Upload artifact
#      uses: actions/upload-artifact@v2
#      with:
#        name: Dragonspeak-${{ steps.unique_string.outputs.unique_string }}.zip
#        path: Dragonspeak-${{ steps.unique_string.outputs.unique_string }}.zip
#
#    - name: Set up Git
#      run: |
#        git config --global user.email "actions@github.com"
#        git config --global user.name "GitHub Actions"
#
#    - name: Create Git tag
#      run: |
#        git tag v${{ steps.unique_string.outputs.unique_string }}
#        git push origin v${{ steps.unique_string.outputs.unique_string }}
#
#    - name: Create release
#      id: create_release
#      uses: softprops/action-gh-release@v1
#      with:
#        files: Dragonspeak-${{ steps.unique_string.outputs.unique_string }}.zip
#        tag_name: v${{ steps.unique_string.outputs.unique_string }}
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Store release URL
      id: release_url
      run: echo "::set-output name=release_url::${{ steps.create_release.outputs.upload_url }}"
    
    - name: Display release URL
      run: |
        echo "Release URL: ${{ steps.release_url.outputs.release_url }}"
