name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: pull latest and rename the existing file
      run: |
        git config --global user.email "conleybear06@gmail.com"
        git config --global user.name "Stonley890"
        git config pull.rebase false
        git pull
        # Find the current commit count
        commit_count=$(git rev-list --count HEAD)
        # Generate the new filename with the commit count
        new_filename="Dragonspeak$commit_count.zip"

    - name: Create Release
      id: create_release
      run: |
        RELEASE_ID=$(curl -s -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/releases \
          -d '{
            "tag_name": "temp-tag",
            "name": "Temporary Release",
            "body": "Temporary release created without a tag.",
            "draft": false,
            "prerelease": false
          }' | jq -r .id)

        # Upload the asset to the release
        curl -s -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/zip" \
          --data-binary @"$new_filename" \
          "https://uploads.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets?name=$new_filename"

        echo "Release ID: $RELEASE_ID"

    - name: Delete the temporary tag
      run: git push origin --delete tmp-release

    - name: Get Release URL
      run: |
        echo "Release URL: ${{ steps.create_release.outputs.upload_url }}"